client_id = "37d8ba13e93020bf2c682c37151c6510"  # Keep your new one
name = "MetaObjectPaginator"
application_url = "https://meta-object-paginator.vercel.app"  
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"  # Match server.js API_VERSION

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_metaobjects,read_products,read_files,write_app_proxy"  # Add these for COA fetch/proxy

[auth]
redirect_urls = [ "https://meta-object-paginator.vercel.app/auth/callback" ]  # Match server.js route